= Top Ruby screencast resources
Orest Ivasiv
2009-06-03
:jbake-type: post
:jbake-status: published
:jbake-tags: ruby, rails, screencast
:source-highlighter: prettify
:icons: font
:my-image-dir: /images

As you know there are several way to kick-off and learn a new
programming language, environment or special tools:

* tutorial
* screencast

But, now screencast is more popular for effective start and feature
demonstration. So, I'm trying to collect as more as possible screencast
resources for learning Ruby and Rails. +

* http://railscasts.com/[http://railscasts.com], it's the most popular
free Rails screencasts
* http://sdruby.com/[http://sdruby.com], it's San Diego's Ruby
community, there are about 59 Ruby and Rails screencasts
* http://www.rubyplus.org/episodes, Free Ruby and Rails Screencast,
about 93 episodes
* http://www.tekniqal.com/[http://www.tekniqal.com], there are 17
tutorials covering basic Ruby topics
* http://www.confreaks.com/events, here is located videos from several
Ruby conferences
* http://showmedo.com/videotutorials/ruby and
http://showmedo.com/videotutorials/rubyonrails, it's great resource for
learning from ground up. There are a lot of interesting videos for
beginners. Also, this resource includes other areas, not only Ruby/Rails
related
* http://www.bestechvideos.com/category/development/ruby[http://www.bestechvideos.com/tag/ruby-on-rails]
and http://www.bestechvideos.com/category/development/ruby, video
collection from different conferences, presentations, etc.   
* http://railslab.newrelic.com/scaling-rails there are educational
videos, teaching you just about everything you need to know to create a
Rails application that can scale
* http://rubytu.be/[http://rubytu.be] is a community driven collection
of Ruby related videos and screencasts 
* http://www.learnivore.com/[http://www.learnivore.com] is another great
screencast aggregator 
* http://www.teachmetocode.com/screencasts is similar to railscast.com
but have less posts, it's worth to look into        
